coverageDetails ::= "[" space (coverageDetails-item ("," space coverageDetails-item)*)? "]" space
coverageDetails-item ::= "{" space coverageDetails-item-coverageType-kv "," space coverageDetails-item-coverageAmount-kv "}" space
coverageDetails-item-coverageAmount-kv ::= "\"coverageAmount\"" space ":" space number
coverageDetails-item-coverageType-kv ::= "\"coverageType\"" space ":" space string
coverageDetails-kv ::= "\"coverageDetails\"" space ":" space coverageDetails
decimal-part ::= [0-9]+
integral-part ::= [0] | [1-9] [0-9]*
number ::= ("-"? integral-part) ("." decimal-part)? ([eE] [-+]? integral-part)? space
policyholder ::= "{" space policyholder-name-kv "," space policyholder-address-kv "," space policyholder-phone-kv "}" space
policyholder-address-kv ::= "\"address\"" space ":" space string
policyholder-kv ::= "\"policyholder\"" space ":" space policyholder
policyholder-name-kv ::= "\"name\"" space ":" space string
policyholder-phone-kv ::= "\"phone\"" space ":" space string
premium ::= "{" space premium-amount-kv "," space premium-frequency-kv "}" space
premium-amount-kv ::= "\"amount\"" space ":" space number
premium-frequency-kv ::= "\"frequency\"" space ":" space string
premium-kv ::= "\"premium\"" space ":" space premium
root ::= "{" space policyholder-kv "," space coverageDetails-kv "," space premium-kv "}" space
space ::= ([ĊĠ     ] space)?
string ::= "\"" [ĠĊ !#-\[\]-~]* "\"" space